StylesPath = .vale-config-files/styles
MinAlertLevel = suggestion
Vocab = Thesis, spectrocloud-vocab
SentenceLength = 30

Packages = Google, proselint, write-good, https://github.com/spectrocloud/spectro-vale-pkg/releases/latest/download/spectrocloud.zip



[*.{tex}]
BasedOnStyles = Vale, ThesisStyle
# BasedOnStyles = ThesisStyle, Google
# BasedOnStyles = ThesisStyle, write-good
# BasedOnStyles = ThesisStyle, proselint
# BasedOnStyles = ThesisStyle, spectrocloud